name: Test Update Documentation Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test-update-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Call Update Documentation Action
      uses: ./
      with:
        main_repo_owner: 'rspcunningham'
        main_repo_name: 'auto-documentator'
        main_github_directory_path: '.'
        docs_repo_owner: 'rspcunningham'
        docs_repo_name: 'auto-documentator'
        docs_github_directory_path: 'docs_test'
        github_token: ${{ secrets.GITHUB_TOKEN }}